// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPGQcnC9VTXsgdCNA3b2IwrwrxmV5hCgw',
    appId: '1:939449096588:web:ac266bb26dbc6d91eadea9',
    messagingSenderId: '939449096588',
    projectId: 'firestoreflutter-95914',
    authDomain: 'firestoreflutter-95914.firebaseapp.com',
    storageBucket: 'firestoreflutter-95914.firebasestorage.app',
    measurementId: 'G-7CJ26HPG3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZWzhH23AQDexvz8Nvy3tJuZBXj0Xnliw',
    appId: '1:939449096588:android:08aa32845c0c1556eadea9',
    messagingSenderId: '939449096588',
    projectId: 'firestoreflutter-95914',
    storageBucket: 'firestoreflutter-95914.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOoIXoGNhsvKZqB02PXLr85ISFZhyxhow',
    appId: '1:939449096588:ios:7bd1e31a26ba107eeadea9',
    messagingSenderId: '939449096588',
    projectId: 'firestoreflutter-95914',
    storageBucket: 'firestoreflutter-95914.firebasestorage.app',
    iosBundleId: 'com.example.stateManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOoIXoGNhsvKZqB02PXLr85ISFZhyxhow',
    appId: '1:939449096588:ios:7bd1e31a26ba107eeadea9',
    messagingSenderId: '939449096588',
    projectId: 'firestoreflutter-95914',
    storageBucket: 'firestoreflutter-95914.firebasestorage.app',
    iosBundleId: 'com.example.stateManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPGQcnC9VTXsgdCNA3b2IwrwrxmV5hCgw',
    appId: '1:939449096588:web:f9fa56b4f2679407eadea9',
    messagingSenderId: '939449096588',
    projectId: 'firestoreflutter-95914',
    authDomain: 'firestoreflutter-95914.firebaseapp.com',
    storageBucket: 'firestoreflutter-95914.firebasestorage.app',
    measurementId: 'G-S6ENQXDXPF',
  );

}